trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  webAppName: 'ita-dataloader-reporting-dev'
  azureServiceConnection: 'ITAARMServiceConnection01'
  containerRegestryServiceConnection: '<container-registry-name>'
  imageName: 'itadataloader.azurecr.io/ita-dataloader-reporting'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: Install Node
  - script: |
      ./build.sh
    displayName: Build project artifacts
  - task: Docker@2
    displayName: Build & Push docker image
    inputs:
      containerRegistry: $(containerRegestryServiceConnection)
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: 'latest'
  - task: AzureAppServiceManage@0
    displayName: Restart App Service
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      Action: 'Restart Azure App Service'
      WebAppName: '$(webAppName)'