kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
  labels:
    app: ita-power-bi-gateway
spec:
  template:
    metadata:
      labels:
        app: ita-power-bi-gateway
    spec:
      containers:
      - name: ita-power-bi-gateway
        image: itadrupalprodeast1.azurecr.io/ita-powerbi-gateway:#{Release.Artifacts._InternationalTradeAdministration.ita-powerbi-gateway.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TENANT_ID
            value: #{TENANT_ID}#
          - name: CLIENT_ID
            value: #{CLIENT_ID}#
          - name: CLIENT_SECRET
            value: #{CLIENT_SECRET}#
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: ita-power-bi-gateway
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  rules:
    - host: powerbi.trade.gov
      http:
        paths:
          - path: /
            backend:
              serviceName: ita-power-bi-gateway
              servicePort: 80
  tls:
    - secretName: trade-gov-tls-secret