kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
  labels:
    app: ita-power-bi-gateway
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 2
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ita-power-bi-gateway
    spec:
      containers:
      - name: ita-power-bi-gateway
        image: itadevacr.azurecr.io/ita-powerbi-gateway:#{Release.Artifacts._InternationalTradeAdministration.ita-powerbi-gateway.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TENANT_ID
            value: #{PBI_TENANT_ID}#
          - name: CLIENT_ID
            value: #{PBI_CLIENT_ID}#
          - name: CLIENT_SECRET
            value: #{PBI_CLIENT_SECRET}#
          - name: WORKSPACE_ID
            value: #{PBI_WORKSPACE_ID}#
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: ita-power-bi-gateway
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  rules:
    - host: powerbi-gateway-itadev2.vangos-cloudapp.us
      http:
        paths:
          - path: /
            backend:
              serviceName: ita-power-bi-gateway
              servicePort: 80
  tls:
    - hosts:
        - powerbi-gateway-itadev2.vangos-cloudapp.us
      secretName: tls-secret