spring:
  profiles: development
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
build-id: n/a
powerbi:
  client-id: ${POWERBI_CLIENT_ID}
  client-secret: ${POWERBI_CLIENT_SECRET}
  tenant-id: ${POWERBI_TENANT_ID}
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:ita
    username: SA
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
build-id: n/a
powerbi:
  client-id: "fake-client-id"
  client-secret: "fake-client-secret"
  tenant-id: "fake-tenant-id"
api:
  token: "fake-token"
---
spring:
  profiles: staging
  datasource:
    url: jdbc:sqlserver://inta-sqla-01.database.windows.net:1433;database=Inta-dataloader-01;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_OAUTH_CLIENT_ID}
            client-secret: ${AZURE_OAUTH_CLIENT_SECRET}
azure:
  activedirectory:
    tenant-id: ${AZURE_OAUTH_TENANT_ID}
    active-directory-groups: TSI_AllUsers
build-id: ${BUILD_ID}
powerbi:
  client-id: ${POWERBI_CLIENT_ID}
  client-secret: ${POWERBI_CLIENT_SECRET}
  tenant-id: ${POWERBI_TENANT_ID}
api:
  token: ${GATEWAY_API_TOKEN}
---
spring:
  profiles: production
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
build-id: ${BUILD_ID}
powerbi:
  client-id: ${POWERBI_CLIENT_ID}
  client-secret: ${POWERBI_CLIENT_SECRET}
  tenant-id: ${POWERBI_TENANT_ID}
api:
  token: ${GATEWAY_API_TOKEN}
