spring:
  profiles: development
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
build-id: n/a
powerbi:
  client-id: ${POWERBI_CLIENT_ID}
  client-secret: ${POWERBI_CLIENT_SECRET}
  tenant-id: ${POWERBI_TENANT_ID}
---
spring:
  profiles: production
  datasource:
    url: ${FLYWAY_URL}
    username: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
build-id: ${BUILD_ID}
powerbi:
  client-id: ${POWERBI_CLIENT_ID}
  client-secret: ${POWERBI_CLIENT_SECRET}
  tenant-id: ${POWERBI_TENANT_ID}